agents/urls.py
from django.urls import path
from .views import AgentListView, AgentDetailView, AgentCreateView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent_list'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent_detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent_update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent_delete'),
    path('create/', AgentCreateView.as_view(), name='agent_create')
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from leads.views import SignUpView, LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing_page'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

leads/urls.py
from django.urls import path
from .views import LeadListView, LeadDetailView, LeadUpdateView, LeadCreateView, LeadDeleteView

app_name = 'leads'

urlpatterns = [
    path('', LeadListView.as_view(), name='lead_list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead_detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead_update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead_delete'),
    path('create/', LeadCreateView.as_view(), name='lead_create'),
]

agents/models.py
from django.db import models

# Create your models here.

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save

# Create your models here.

class User(AbstractUser):
  is_organiser = models.BooleanField(default=True)
  is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
  user = models.OneToOneField("User", on_delete=models.CASCADE)

  def __str__(self):
      return self.user.username
  

class Lead(models.Model):
  first_name = models.CharField(max_length=30)
  last_name = models.CharField(max_length=30)
  age = models.IntegerField(default=0)
  organisation = models.ForeignKey("Userprofile", on_delete=models.CASCADE)
  agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)

  def __str__(self):
    return f"{self.first_name}{self.last_name}"


class Agent(models.Model):
  user = models.OneToOneField("User", on_delete=models.CASCADE)
  organisation = models.ForeignKey("Userprofile", on_delete=models.CASCADE)

  def __str__(self):
    return self.user.email


def post_save_user_signal(sender, instance, created, **kwargs):
  if created:
    UserProfile.objects.create(user=instance)


post_save.connect(post_save_user_signal, sender=User)

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class AgentModelForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ('email', 'username',
    'first_name', 'last_name', 'date_joined')

leads/forms.py
from django import forms
from .models import Lead
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UsernameField

User = get_user_model()


class LeadModelForm(forms.ModelForm):
  class Meta:
    model = Lead
    fields = ('first_name', 'last_name', 'age', 'agent')


class CustomUserCreationForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ("username",)
    field_classes = {'username': UsernameField}

agents/views.py
from django.shortcuts import render, reverse
from django.views import generic
from leads.models import Agent
from .forms import AgentModelForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import LoginAndOrganiserRequiredMixin


class AgentListView(LoginAndOrganiserRequiredMixin,generic.ListView):
  template_name = 'agents/agent_list.html'
  context_object_name = 'agents'

  def get_queryset(self):
    user = self.request.user
    if user.is_organiser:
      queryset = Agent.objects.filter(organisation=user.userprofile)
    return queryset


class AgentDetailView(LoginAndOrganiserRequiredMixin, generic.DetailView):
  template_name = 'agents/agent_detail.html'
  context_object_name = 'agent'

  def get_queryset(self):
    user = self.request.user
    if user.is_organiser:
      queryset = Agent.objects.filter(organisation=user.userprofile)
    return queryset


class AgentCreateView(LoginAndOrganiserRequiredMixin, generic.CreateView):
  template_name = 'agents/agent_create.html'
  form_class = AgentModelForm

  def get_success_url(self):
    return reverse('agents:agent_list')

  def form_valid(self, form):
    user = form.save(commit=False)
    user.is_organiser = False
    user.is_agent = True
    user.save()
    Agent.objects.create(
      user=user,
      organisation=self.request.user.userprofile
    )
    return super(AgentCreateView, self).form_valid(form)

  def get_queryset(self):
    user = self.request.user
    if user.is_organiser:
      queryset = Agent.objects.filter(organisation=user.userprofile)
    return queryset


class AgentUpdateView(LoginAndOrganiserRequiredMixin, generic.UpdateView):
  template_name = 'agents/agent_update.html'
  form_class = AgentModelForm

  def get_success_url(self):
    return reverse('agents:agent_list')

  def get_queryset(self):
    user = self.request.user
    if user.is_organiser:
      queryset = Agent.objects.filter(organisation=user.userprofile)
    return queryset


class AgentDeleteView(LoginAndOrganiserRequiredMixin, generic.DeleteView):
  template_name = 'agents/agent_delete.html'
  form_class = None

  def get_success_url(self):
    return reverse('agents:agent_list')

  def get_queryset(self):
    user = self.request.user
    if user.is_organiser:
      queryset = Agent.objects.filter(organisation=user.userprofile)
    return queryset

leads/views.py
from django.shortcuts import render, reverse
from django.views import generic
from .models import Lead
from .forms import LeadModelForm, CustomUserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import LoginAndOrganiserRequiredMixin


class SignUpView(generic.CreateView):
  template_name = 'registration/signup.html'
  from_class = CustomUserCreationForm

  def get_success_url(self):
    return reverse('leads:lead_list')

class LandingPageView(generic.TemplateView):
  template_name = 'landing_page.html'


class LeadListView(LoginRequiredMixin,generic.ListView):
  template_name = 'leads/lead_list.html'
  context_object_name = 'leads'

  def get_queryset(self):
    user = self.request.user
    if user.is_organiser:
      queryset = Lead.objects.filter(organisation=user.userprofile)
    else:
      queryset = Lead.objects.filter(organisation=user.agent.organisation)
      queryset = queryset.filter(agent__user=user)
    return  queryset


class LeadDetailView(LoginRequiredMixin, generic.DetailView):
  template_name = 'leads/lead_detail.html'
  context_object_name = 'lead'

  def get_queryset(self):
    return Lead.objects.all()


class LeadUpdateView(LoginRequiredMixin, generic.UpdateView):
  template_name = 'leads/lead_update.html'
  form_class = LeadModelForm

  def get_success_url(self):
    return reverse('leads:lead_list')
  
  def get_queryset(self):
    organisation = self.request.user.userprofile
    queryset = Lead.objects.filter(organisation=organisation)
    return queryset
  
  def form_valid(self, form):
    lead = form.save(commit=False)
    lead.organisation = self.request.user.userprofile
    lead.save()
    return super(LeadUpdateView, self).form_valid(form)
  

class LeadCreateView(LoginAndOrganiserRequiredMixin, generic.CreateView):
  template_name = 'leads/lead_create.html'
  form_class = LeadModelForm

  def get_queryset(self):
    organisation = self.request.user.userprofile
    queryset = Lead.objects.filter(organisation=organisation)
    return queryset

  def get_success_url(self):
    return reverse('leads:lead_list')

  def form_valid(self, form):
    lead = form.save(commit=False)
    lead.organisation = self.request.user.userprofile
    lead.save()
    return super(LeadCreateView, self).form_valid(form)

  
class LeadDeleteView(LoginAndOrganiserRequiredMixin, generic.DeleteView):
  template_name = 'leads/lead_delete.html'
  context_object_name = 'lead'

  def get_success_url(self):
    return reverse('leads:lead_list')

  def get_queryset(self):
    return Lead.objects.all()

agents/templates/agents/agent_create.html
{% extends 'base.html' %}


{% block content %} 
<h1>Welcome to the create Agent page</h1>
<a href="{% url 'agents:agent_list'%}">Back to the Agents</a>
<hr>
<form action="." method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>

{% endblock %}

agents/templates/agents/agent_delete.html
{% extends 'base.html' %}


{% block title %} {% endblock %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Submit</button>
</form>
  
{% endblock  %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block title %} {% endblock %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden" style="user-select: auto;">
  <div class="container px-5 py-24 mx-auto" style="user-select: auto;">
    <div class="lg:w-4/5 mx-auto flex flex-wrap" style="user-select: auto;">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0" style="user-select: auto;">
        <h2 class="text-sm title-font text-gray-500 tracking-widest" style="user-select: auto;">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4" style="user-select: auto;">
          {{agent.user.username}}</h1>
        <div class="flex mb-4" style="user-select: auto;">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1" style="user-select: auto;">Description</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1" style="user-select: auto;">Reviews</a>
          <a href="{% url 'agents:agent_update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1" style="user-select: auto;">Update</a>
        </div>
        <p class="leading-relaxed mb-4" style="user-select: auto;">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2" style="user-select: auto;">
          <span class="text-gray-500" style="user-select: auto;">Age</span>
          <span class="ml-auto text-gray-900" style="user-select: auto;"></span>
        </div>
        <div class="flex border-t border-gray-200 py-2" style="user-select: auto;">
          <span class="text-gray-500" style="user-select: auto;">Location</span>
          <span class="ml-auto text-gray-900" style="user-select: auto;">Dummy Location</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2" style="user-select: auto;">
          <span class="text-gray-500" style="user-select: auto;">Phone Number</span>
          <span class="ml-auto text-gray-900" style="user-select: auto;">18341328396</span>
        </div>
        <div class="flex" style="user-select: auto;">
          <a href="{% url 'agents:agent_delete' agent.pk %}"class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" style="user-select: auto;">Delete</a>
          
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400" style="user-select: auto;">
    </div>
  </div>
</section>
  
{% endblock %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block title %} {% endblock %}

{% block content %}

<section class="text-gray-600 body-font" style="user-select: auto;">
  <div class="container px-5 py-24 mx-auto flex flex-wrap" style="user-select: auto;">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
      <div class="">
        <h1 class="text-4xl text-gray-800">Leads</h1>
      </div>
      <div class="text-gray-500 hover:text-blue-500">
        {% if request.user.is_organiser %}
          <a href="{% url 'agents:agent_create' %}">Create New Agent</a>
        {% endif %}
      </div>
    </div>
    <div class="flex flex-wrap -m-4" style="user-select: auto;">
      {% for agent in agents %}
        <div class="p-4 lg:w-1/2 md:w-full" style="user-select: auto;">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col" style="user-select: auto;">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0" style="user-select: auto;">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24" style="user-select: auto;">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2" style="user-select: auto;"></path>
              </svg>
            </div>
            <div class="flex-grow" style="user-select: auto;">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3" style="user-select: auto;">{{agent.user.first_name}} {{agent.user.last_name}}</h2>
              <p class="leading-relaxed text-base" style="user-select: auto;">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
              <a href="{% url 'agents:agent_detail' agent.pk %}" class="mt-3 text-indigo-500 inline-flex items-center" style="user-select: auto;">View This Lead
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24" style="user-select: auto;">
                  <path d="M5 12h14M12 5l7 7-7 7" style="user-select: auto;"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>

  
{% endblock %}

agents/templates/agents/agent_update.html
{% extends 'base.html' %}


{% block title %} {% endblock %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden" style="user-select: auto;">
  <div class="container px-5 py-24 mx-auto" style="user-select: auto;">
    <div class="lg:w-4/5 mx-auto flex flex-wrap" style="user-select: auto;">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0" style="user-select: auto;">
        <h2 class="text-sm title-font text-gray-500 tracking-widest" style="user-select: auto;">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4" style="user-select: auto;">{{agent.user.first_name}} {{agent.user.last_name}}</h1>
        <div class="flex mb-4" style="user-select: auto;">
          <a href="{% url 'agents:agent_detail' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1" style="user-select: auto;">Description</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1" style="user-select: auto;">Reviews</a>
          <a href="{% url 'agents:agent_update' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1" style="user-select: auto;">Update</a>
        </div>
        <form action="." method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Submit</button>
        </form>
        <div class="flex" style="user-select: auto;">
          <a href="{% url 'agents:agent_delete' agent.pk %}"class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" style="user-select: auto;">Delete</a>
          
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400" style="user-select: auto;">
    </div>
  </div>
</section>
  
{% endblock %}
 

leads/templates/leads/lead_create.html
{% extends 'base.html' %}


{% block content %} 
<h1>Welcome to the create lead page</h1>
<a href="{% url 'leads:lead_list'%}">Back to the Leads</a>
<hr>
<form action="." method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>

{% endblock %}

leads/templates/leads/lead_delete.html
{% extends 'base.html' %}


{% block title %} {% endblock %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Submit</button>
</form>
  
{% endblock  %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block title %} {% endblock %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden" style="user-select: auto;">
  <div class="container px-5 py-24 mx-auto" style="user-select: auto;">
    <div class="lg:w-4/5 mx-auto flex flex-wrap" style="user-select: auto;">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0" style="user-select: auto;">
        <h2 class="text-sm title-font text-gray-500 tracking-widest" style="user-select: auto;">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4" style="user-select: auto;">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4" style="user-select: auto;">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1" style="user-select: auto;">Description</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1" style="user-select: auto;">Reviews</a>
          <a href="{% url 'leads:lead_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1" style="user-select: auto;">Update</a>
        </div>
        <p class="leading-relaxed mb-4" style="user-select: auto;">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2" style="user-select: auto;">
          <span class="text-gray-500" style="user-select: auto;">Age</span>
          <span class="ml-auto text-gray-900" style="user-select: auto;">{{lead.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2" style="user-select: auto;">
          <span class="text-gray-500" style="user-select: auto;">Location</span>
          <span class="ml-auto text-gray-900" style="user-select: auto;">Dummy Location</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2" style="user-select: auto;">
          <span class="text-gray-500" style="user-select: auto;">Phone Number</span>
          <span class="ml-auto text-gray-900" style="user-select: auto;">18341328396</span>
        </div>
        <div class="flex" style="user-select: auto;">
          <a href="{% url 'leads:lead_delete' lead.pk %}"class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" style="user-select: auto;">Delete</a>
          
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400" style="user-select: auto;">
    </div>
  </div>
</section>
  
{% endblock %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}

{% block title %} {% endblock %}

{% block content %}

<section class="text-gray-600 body-font" style="user-select: auto;">
  <div class="container px-5 py-24 mx-auto flex flex-wrap" style="user-select: auto;">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
      <div class="">
        <h1 class="text-4xl text-gray-800">Leads</h1>
      </div>
      <div class="text-gray-500 hover:text-blue-500">
        {% if request.user.is_organiser %}
          <a href="{% url 'leads:lead_create' %}">Create New Lead</a>
        {% endif %}
      </div>
    </div>
    <div class="flex flex-wrap -m-4" style="user-select: auto;">
      {% for lead in leads %}
        <div class="p-4 lg:w-1/2 md:w-full" style="user-select: auto;">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col" style="user-select: auto;">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0" style="user-select: auto;">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24" style="user-select: auto;">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2" style="user-select: auto;"></path>
              </svg>
            </div>
            <div class="flex-grow" style="user-select: auto;">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3" style="user-select: auto;">{{lead.first_name}} {{lead.last_name}}</h2>
              <p class="leading-relaxed text-base" style="user-select: auto;">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
              <a href="{% url 'leads:lead_detail' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center" style="user-select: auto;">View This Lead
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24" style="user-select: auto;">
                  <path d="M5 12h14M12 5l7 7-7 7" style="user-select: auto;"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>

  
{% endblock %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}


{% block title %} {% endblock %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden" style="user-select: auto;">
  <div class="container px-5 py-24 mx-auto" style="user-select: auto;">
    <div class="lg:w-4/5 mx-auto flex flex-wrap" style="user-select: auto;">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0" style="user-select: auto;">
        <h2 class="text-sm title-font text-gray-500 tracking-widest" style="user-select: auto;">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4" style="user-select: auto;">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4" style="user-select: auto;">
          <a href="{% url 'leads:lead_detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1" style="user-select: auto;">Description</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1" style="user-select: auto;">Reviews</a>
          <a href="{% url 'leads:lead_update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1" style="user-select: auto;">Update</a>
        </div>
        <form action="." method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Submit</button>
        </form>
        <div class="flex" style="user-select: auto;">
          <a href="{% url 'leads:lead_delete' lead.pk %}"class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" style="user-select: auto;">Delete</a>
          
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400" style="user-select: auto;">
    </div>
  </div>
</section>
  
{% endblock %}
 

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  <title>Document</title>
</head>
<body>
  <div class="max-w-5xl mx-auto">
  {% include 'navbar.html' %}
  {% block content %}
    
  {% endblock content %}
  </div>
  
</body>
</html>

templates/landing_page.html
{%  extends 'base.html' %}


{% block content %} 
  <section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">This CRM helps you manage your leads</h1>
      <p class="mb-8 leading-relaxed"> Manage and create Leads for your Agents </p>
      <div class="flex justify-center">
        <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
        <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">DJCRM</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      
    </nav>
    {% if not request.user.is_authenticated %}
    <a href="{% url 'signup' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Signup
    </a>
    {% else %}
    <a href="{% url 'leads:lead_list' %}" class="mr-5 hover:text-gray-900">Leads</a>
    <a  class="mr-5 hover:text-gray-900">Categories</a>
      {% if request.user.is_organiser %}
        <a href="{% url 'agents:agent_list'%}" class="mr-5 hover:text-gray-900">Agents</a>
      {% endif %}
    {% endif %}
    {% if request.user.is_authenticated %}
    In as: {{ request.user.username }}
    <a href="{% url 'logout' %}" class="ml-4  inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Logout
    </a>
    {% else %}
    <a href="{% url 'login' %}" class="ml-4 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
    </a>
    {% endif %}
  </div>
</header>